### ISSUE TITLE
HA 0.81.0 breaks component

### ISSUE THREAD

**Issue by ThaStealth** [marconfus/ha-nefit#15]
Don't know what they changed but it breaks the XMPP implementation:

<TagSet object at 0x7fcd64944da0 tags 0:32:16> not in asn1Spec: <OctetString schema object at 0x7fcd64905cf8 tagSet <TagSet object at 0x7fcd66671a20 tags 0:0:4> encoding iso-8859-1>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1492, in _process
    if not self.__read_xml():
  File "/usr/local/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1564, in __read_xml
    self.__spawn_event(xml)
  File "/usr/local/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1632, in __spawn_event
    handler.prerun(stanza_copy)
  File "/usr/local/lib/python3.6/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 64, in prerun
    self.run(payload, True)
  File "/usr/local/lib/python3.6/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/usr/local/lib/python3.6/site-packages/sleekxmpp/features/feature_starttls/starttls.py", line 64, in _handle_starttls_proceed
    if self.xmpp.start_tls():
  File "/usr/local/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 889, in start_tls
    cert.verify(self._expected_server_name, self._der_cert)
  File "/usr/local/lib/python3.6/site-packages/sleekxmpp/xmlstream/cert.py", line 134, in verify
    cert_names = extract_names(raw_cert)
  File "/usr/local/lib/python3.6/site-packages/sleekxmpp/xmlstream/cert.py", line 73, in extract_names
    asn1Spec=OctetString())[0]
  File "/usr/local/lib/python3.6/site-packages/pyasn1/codec/ber/decoder.py", line 1318, in __call__
    '%s not in asn1Spec: %r' % (tagSet, asn1Spec)
pyasn1.error.PyAsn1Error: <TagSet object at 0x7fcd64944da0 tags 0:32:16> not in asn1Spec: <OctetString schema object at 0x7fcd64905cf8 tagSet <TagSet object at 0x7fcd66671a20 tags 0:0:4> encoding iso-8859-1>

**Comment by snelweg** [comment]
Wow, exactly the same here!

https://community.home-assistant.io/t/nefit-stopped-working-after-upgrade-to-hassio-version-0-81-0/75738

**Comment by marconfus** [comment]
Great! Perhaps because of this change in Homeassistant?
https://github.com/home-assistant/home-assistant/pull/17283

I guess this needs some bigger rewrite...

**Comment by ThaStealth** [comment]
I figured out a littlebit more, it seems they updated the sleekxmpp component from 1.3.2 to 1.3.3, and this breaks the Nefit (and apparently Netflix) plugins.

**Comment by marconfus** [comment]
It's not the first time the sleekxmpp library makes problems. They have implemented their own certificate parser. This is in most cases a very bad idea.
I don't know if the slixmpp library that homeassistant now uses is so much better, as it's a fork of sleekxmpp.

**Comment by snelweg** [comment]
@marconfus thanks for the update. My knowledge of python is non-excistant. Glad that you are willing to look for a solution.
Keep up the good work and thanks again!

**Comment by mories76** [comment]
I found a workaround !
I upgraded from .80.3 to 0.81.5: same issue, then started downgrading sleekxmpp the same way I documented in issue #6 . Didn't work.
Searching for the "TagSet object not in asn1Spec:" pointed towards pyasn1.
Downgraded pyasn1 to a previous versions. I wasn't aware of the pip freeze command which shows all installed pip modules. So reverting to my backup. Ran pip freeze logging it to a file. Upgraded again to 81.5 compared the result of pip freeze for 80.3 and 81.5.
Then I downgraded pyasn1 to version 0.3.7, was upgraded to pyasn 0.4.4.
Bingo !!
I will update the instructions in issue #6. 
Please let me know if this works for you as well

**Comment by meizenga** [comment]
I can confirm downgrading pyasn1 to v0.3.7 works, error is gone, Nefit is working again.

pip install pyasn1==0.3.7

**Comment by marconfus** [comment]
So, I found some time to start a total rewrite of the component and underlying library. It doesn‘t have the featureset of the old component yet, but shouldn‘t have the stupid dependency problems. At the moment only „set manual/automatic mode“ and „set target temperature“. 
I hope I find some more time to add more features. 

https://github.com/marconfus/ha-nefit-ng/blob/master/nefit.py

**Comment by snelweg** [comment]
@marconfus thank you! Much appreciated.

**Comment by mories76** [comment]
@marconfus looking good, I will try tris version coming weekend

**Comment by marklagendijk** [comment]
@marconfus nice!
I just installed it to try it out, and did a small test:
- The information from Nefit appears correctly in Home Assistant.
- Adjusting the mode from `auto` to `manual` and setting the temperature works. I saw the result on the Nefit.
- I see a lot of extra attributes in the state. But they don't have proper names, yet, so I have no clue what they are. I don't see the system pressure in there, yet.
- Changing the mode on the Nefit is reflected in Home Assistant.

State:
```yaml
state: auto
attributes:
  temperature: 22 
  BLE: false
  TOT: 22.0
  current_temperature: 20 
  BBE: false
  supported_features: 129
  ARS: init 
  IHS: ok
  CSP: 36
  friendly_name: CV
  HED_DB:  
  MMT: 22.0
  BAI: No 
  HMD: off
  min_temp: 7
  UMD: clock
  DAS: off
  TSP: 20.0
  operation_list: auto,manual 
  FPA: off
  PMR: false
  TOD: 0
  DHW: on
  IHT: 20.00
  CTR: room
  TOR: off
  CTD: 2019-01-05T13:35:51+00:00 Sa 
  FAH: false
  max_temp: 35
  BMR: false
  TAS: off
  HED_EN: false
  HED_DEV: false
  CPM: auto
  ESI: off
  operation_mode: auto
  DOT: false
  RS: off
```
